// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuymqduavlhdsmppmnga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1eW1xZHVhdmxoZHNtcHBtbmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NTg0NzYsImV4cCI6MjA4NjAzNDQ3Nn0.GxJdWWhL23t81jorBcudRFF2e5jskKY4C_EXBT-7MWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});